### ISSUE TITLE
Failed to create the branch in Octane

### ISSUE THREAD

**Issue by jamesnswithers** [MicroFocus/Create-Branch-External-Action#1]
Hi, i am getting an issue when running the task. The branch is correctly created in GitHub but it fails when creating the branch in Octane with the below error. I have checked if the branch is already created but it is not listed.

Is there anything else I can do or check to fix this issue?

> Error: The branch was created in the SCM Repository, but an error occurred while creating the branch in Octane.Please check if there was an existing branch with the same name for the same repository. If there is, you might need to update its delete status. Additional info: :[{"error_code":"platform.modify_non_editable_field","correlation_id":"xrj2wn860lzd5t0elzjvqwgy4","description":"The field Backlog items for entity scm_repository is not editable and cannot be modified","description_translated":"The field Backlog items for entity scm_repository is not editable and cannot be modified","properties":{"entity_type":"scm_repository","field_name":"Backlog items"},"business_error":true}] at C:\github\microfocus\Create-Branch-External-Action\dist\server.js:346:23 at Generator.next () at fulfilled (C:\github\microfocus\Create-Branch-External-Action\dist\server.js:20:58) at processTicksAndRejections (node:internal/process/task_queues:93:5)

**Comment by SurubariuRazvan** [comment]
What Octane version are you using?

**Comment by jamesnswithers** [comment]
We have saas version 16.0.116.68. Not sure the required version for this action?

**Comment by SurubariuRazvan** [comment]
The last release was for version 15.1.90. From Octane version 16.0.x the APIs have changed and some changes were required.
Soon a new release compatible with 16.0.x will be published.

**Comment by jamesnswithers** [comment]
ah got it! @SurubariuRazvan thanks for confirming that for me.

**Comment by SurubariuRazvan** [comment]
The release for 16.0.100 is out now. Your issue should be resolved in this version.
